name: tachidesk_sorayomi_re
description: A new Flutter project.

publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=2.17.5 <3.0.0"

dependencies:
  cached_network_image: ^3.2.1
  dio: ^4.0.6
  easy_localization: ^3.0.1
  flutter:
    sdk: flutter
  flutter_mobx: ^2.0.6+1
  fluttertoast: ^8.0.9
  freezed_annotation: ^2.0.3
  get_it: ^7.2.0
  go_router: ^4.1.0
  hive: ^2.2.2
  hive_flutter: ^1.1.0
  infinite_scroll_pagination: ^3.2.0
  intl: ^0.17.0
  json_annotation: ^4.5.0
  mobx: ^2.0.7+4
  path_provider: ^2.0.11
  share_plus: ^4.0.10

dev_dependencies:
  build_runner: ^2.1.11
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
  freezed: ^2.0.3+1
  go_router_builder: ^1.0.6
  hive_generator: ^1.1.3
  json_serializable: ^6.2.0
  lints: ^2.0.0
  mobx_codegen: ^2.0.7

flutter:
  uses-material-design: true
